# Generated by Django 5.2.5 on 2025-10-07 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_etl19_logs_unificados'),
        ('core', '0003_contabilidade_endereco_cobranca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoGestk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(db_index=True, help_text='Número único do contrato GESTK', max_length=50, unique=True)),
                ('data_inicio', models.DateField(db_index=True, help_text='Data de início do contrato')),
                ('data_termino', models.DateField(blank=True, db_index=True, help_text='Data de término do contrato (NULL = sem prazo definido)', null=True)),
                ('data_renovacao', models.DateField(blank=True, help_text='Data de renovação do contrato', null=True)),
                ('plano_servico', models.CharField(db_index=True, help_text='Código do plano de serviço (basic, pro, enterprise)', max_length=50)),
                ('modulos_inclusos', models.JSONField(default=list, help_text='Lista de módulos inclusos no contrato')),
                ('limites_usuarios', models.IntegerField(default=5, help_text='Limite de usuários simultâneos')),
                ('limites_empresas', models.IntegerField(default=10, help_text='Limite de empresas que podem ser gerenciadas')),
                ('limites_contratos_internos', models.IntegerField(default=100, help_text='Limite de contratos internos (clientes da contabilidade)')),
                ('valor_mensal', models.DecimalField(decimal_places=2, help_text='Valor mensal do contrato', max_digits=10)),
                ('valor_anual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor anual do contrato (se houver desconto)', max_digits=10, null=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de desconto aplicado', max_digits=5)),
                ('dia_vencimento', models.IntegerField(default=10, help_text='Dia do mês para vencimento das faturas')),
                ('status', models.CharField(choices=[('trial', 'Período de Teste'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], db_index=True, default='ativo', help_text='Status atual do contrato', max_length=20)),
                ('motivo_suspensao', models.CharField(blank=True, help_text='Motivo da suspensão do contrato', max_length=255, null=True)),
                ('data_suspensao', models.DateField(blank=True, help_text='Data da suspensão do contrato', null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, help_text='Motivo do cancelamento do contrato', max_length=255, null=True)),
                ('data_cancelamento', models.DateField(blank=True, help_text='Data do cancelamento do contrato', null=True)),
                ('responsavel_financeiro_nome', models.CharField(blank=True, help_text='Nome do responsável financeiro', max_length=100, null=True)),
                ('responsavel_financeiro_email', models.EmailField(blank=True, help_text='E-mail do responsável financeiro', max_length=254, null=True)),
                ('responsavel_financeiro_telefone', models.CharField(blank=True, help_text='Telefone do responsável financeiro', max_length=20, null=True)),
                ('endereco_cobranca', models.JSONField(blank=True, default=dict, help_text='Endereço para cobrança (JSON com logradouro, cidade, etc.)')),
                ('trial_ate', models.DateField(blank=True, help_text='Data limite do período de teste', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o contrato', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contabilidade', models.OneToOneField(help_text='Escritório de contabilidade cliente da GESTK', on_delete=django.db.models.deletion.CASCADE, related_name='contrato_gestk', to='core.contabilidade')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_gestk_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato GESTK',
                'verbose_name_plural': 'Contratos GESTK',
                'db_table': 'administracao_contratos_gestk',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'data_inicio'], name='administrac_status_59872a_idx'), models.Index(fields=['plano_servico', 'status'], name='administrac_plano_s_92211a_idx'), models.Index(fields=['data_termino'], name='administrac_data_te_947213_idx'), models.Index(fields=['trial_ate'], name='administrac_trial_a_3978db_idx'), models.Index(fields=['numero_contrato'], name='administrac_numero__5c2c91_idx')],
            },
        ),
    ]
