# Generated by Django 5.2.5 on 2025-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos', 'Pós-graduação')], max_length=30, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero'),
        ),
    ]
