# Generated by Django 5.2.5 on 2025-10-07 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_custom_user_model'),
        ('pessoas', '0011_contrato_limites_empresas_contrato_limites_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabilidade',
            name='endereco_cobranca',
            field=models.JSONField(blank=True, default=dict, help_text='Endereço para cobrança (JSON com logradouro, cidade, etc.)', verbose_name='Endereço de Cobrança'),
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='responsavel_financeiro_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Responsável Financeiro - E-mail'),
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='responsavel_financeiro_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável Financeiro - Nome'),
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='responsavel_financeiro_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Responsável Financeiro - Telefone'),
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='saldo_creditos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo de Créditos'),
        ),
        migrations.AddField(
            model_name='contabilidade',
            name='suspensa_por_inadimplencia',
            field=models.BooleanField(default=False, verbose_name='Suspensa por Inadimplência'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='endereco_cobranca',
            field=models.JSONField(blank=True, default=dict, help_text='Endereço para cobrança (JSON com logradouro, cidade, etc.)', verbose_name='Endereço de Cobrança'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='responsavel_financeiro_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Responsável Financeiro - E-mail'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='responsavel_financeiro_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável Financeiro - Nome'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='responsavel_financeiro_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Responsável Financeiro - Telefone'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='saldo_creditos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo de Créditos'),
        ),
        migrations.AddField(
            model_name='historicalcontabilidade',
            name='suspensa_por_inadimplencia',
            field=models.BooleanField(default=False, verbose_name='Suspensa por Inadimplência'),
        ),
        migrations.AddField(
            model_name='historicalusuario',
            name='ultima_contabilidade',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Contabilidade mais recentemente acessada pelo usuário', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contabilidade', verbose_name='Última Contabilidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_contabilidade',
            field=models.ForeignKey(blank=True, help_text='Contabilidade mais recentemente acessada pelo usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_ultimo_acesso', to='core.contabilidade', verbose_name='Última Contabilidade'),
        ),
        migrations.CreateModel(
            name='UsuarioAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa_cnpj', models.CharField(blank=True, db_index=True, help_text='CNPJ da empresa específica (se o acesso for restrito)', max_length=20, null=True)),
                ('role', models.CharField(choices=[('superuser', 'Superusuário'), ('admin', 'Administrador'), ('operacional', 'Operacional'), ('etl', 'ETL'), ('readonly', 'Somente Leitura')], db_index=True, default='operacional', help_text='Papel do usuário nesta contabilidade', max_length=20)),
                ('modulos_acesso', models.JSONField(default=list, help_text='Módulos que o usuário pode acessar nesta contabilidade')),
                ('data_inicio', models.DateField(db_index=True, help_text='Data de início do acesso')),
                ('data_fim', models.DateField(blank=True, db_index=True, help_text='Data de fim do acesso (NULL = sem prazo definido)', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Se o acesso está ativo')),
                ('mfa_required', models.BooleanField(default=False, help_text='MFA obrigatório para este acesso')),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list, help_text='Faixas de IP permitidas (CIDR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contabilidade', models.ForeignKey(help_text='Contabilidade acessível', on_delete=django.db.models.deletion.CASCADE, related_name='acessos_usuarios', to='core.contabilidade')),
                ('contrato', models.ForeignKey(blank=True, help_text='Contrato específico (se o acesso for restrito a um cliente)', null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.contrato')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou este acesso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuário que tem acesso', on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso de Usuário',
                'verbose_name_plural': 'Acessos de Usuários',
                'db_table': 'core_usuario_acessos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'ativo', 'data_inicio'], name='core_usuari_usuario_990cb9_idx'), models.Index(fields=['contabilidade', 'ativo', 'data_inicio'], name='core_usuari_contabi_90fc41_idx'), models.Index(fields=['role', 'ativo'], name='core_usuari_role_4350ea_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='core_usuari_data_in_4049d1_idx'), models.Index(fields=['empresa_cnpj', 'ativo'], name='core_usuari_empresa_26c2b8_idx')],
                'unique_together': {('usuario', 'contabilidade', 'contrato'), ('usuario', 'contabilidade', 'empresa_cnpj')},
            },
        ),
    ]
