# Generated by Django 5.2.5 on 2025-10-22 18:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_contabilidade_endereco_cobranca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFaturamentoEmpresa',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('object_id', models.UUIDField()),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(db_index=True, verbose_name='Mês')),
                ('total_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Saídas')),
                ('total_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Serviços')),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Geral')),
                ('data_importacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Importação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contabilidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contabilidade', verbose_name='Contabilidade')),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'model__in': ['pessoajuridica', 'pessoafisica']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Faturamento da Empresa',
                'verbose_name_plural': 'historical Faturamentos das Empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FaturamentoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(db_index=True, verbose_name='Mês')),
                ('total_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Saídas')),
                ('total_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Serviços')),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Geral')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos_empresas', to='core.contabilidade', verbose_name='Contabilidade')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['pessoajuridica', 'pessoafisica']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Faturamento da Empresa',
                'verbose_name_plural': 'Faturamentos das Empresas',
                'db_table': 'gestao_faturamento_empresas',
                'ordering': ['-ano', '-mes', 'contabilidade__razao_social'],
                'indexes': [models.Index(fields=['contabilidade', 'ano', 'mes'], name='gestao_fatu_contabi_157b57_idx'), models.Index(fields=['ano', 'mes'], name='gestao_fatu_ano_391e1b_idx'), models.Index(fields=['data_importacao'], name='gestao_fatu_data_im_c6676f_idx')],
                'unique_together': {('contabilidade', 'content_type', 'object_id', 'ano', 'mes')},
            },
        ),
    ]
