# Generated by Django 5.2.5 on 2025-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_capitalsocial_quadrosocietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpessoafisica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='endereco',
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
    ]
