# Generated by Django 5.2.5 on 2025-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_remove_historicalpessoafisica_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='limites_empresas',
            field=models.IntegerField(default=1, help_text='Limite de empresas que este cliente pode gerenciar', verbose_name='Limite de Empresas'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='limites_usuarios',
            field=models.IntegerField(default=1, help_text='Limite de usuários que podem acessar este cliente', verbose_name='Limite de Usuários'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modulos_contratados',
            field=models.JSONField(default=list, help_text='Lista de módulos contratados para este cliente', verbose_name='Módulos Contratados'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plano_servico',
            field=models.CharField(blank=True, help_text='Código do plano de serviço contratado', max_length=50, null=True, verbose_name='Plano de Serviço'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='status_cobranca',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=20, verbose_name='Status de Cobrança'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='limites_empresas',
            field=models.IntegerField(default=1, help_text='Limite de empresas que este cliente pode gerenciar', verbose_name='Limite de Empresas'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='limites_usuarios',
            field=models.IntegerField(default=1, help_text='Limite de usuários que podem acessar este cliente', verbose_name='Limite de Usuários'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='modulos_contratados',
            field=models.JSONField(default=list, help_text='Lista de módulos contratados para este cliente', verbose_name='Módulos Contratados'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='plano_servico',
            field=models.CharField(blank=True, help_text='Código do plano de serviço contratado', max_length=50, null=True, verbose_name='Plano de Serviço'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='status_cobranca',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=20, verbose_name='Status de Cobrança'),
        ),
    ]
