# Generated by Django 5.2.5 on 2025-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_contrato_limites_empresas_contrato_limites_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='ramo_atividade',
            field=models.CharField(blank=True, choices=[('comercio', 'Comércio'), ('industria', 'Indústria'), ('servicos', 'Serviços')], max_length=20, null=True, verbose_name='Ramo de Atividade'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='regime_fiscal',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=20, null=True, verbose_name='Regime Fiscal'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='ramo_atividade',
            field=models.CharField(blank=True, choices=[('comercio', 'Comércio'), ('industria', 'Indústria'), ('servicos', 'Serviços')], max_length=20, null=True, verbose_name='Ramo de Atividade'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='regime_fiscal',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=20, null=True, verbose_name='Regime Fiscal'),
        ),
    ]
