# Generated by Django 5.2.5 on 2025-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_historicalpessoajuridica_ramo_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cae',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAE'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='certificado_digital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Certificado Digital'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cnae',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cnae_20',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE 2.0'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='contador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='data_inatividade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Inatividade'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='data_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término do Contrato'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='duracao_contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração do Contrato (meses)'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='email_resp_legal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Responsável Legal'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='motivo_inatividade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Inatividade'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='situacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='usa_cnae_20',
            field=models.BooleanField(default=False, verbose_name='Usa CNAE 2.0'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cae',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAE'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='certificado_digital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Certificado Digital'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cnae',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cnae_20',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE 2.0'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='contador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='data_inatividade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Inatividade'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='data_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término do Contrato'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='duracao_contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração do Contrato (meses)'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='email_resp_legal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Responsável Legal'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='motivo_inatividade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Inatividade'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='situacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='usa_cnae_20',
            field=models.BooleanField(default=False, verbose_name='Usa CNAE 2.0'),
        ),
    ]
