# Generated by Django 5.2.5 on 2025-10-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0013_historicalpessoajuridica_cae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='cnae',
        ),
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='cnae_20',
        ),
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='regime_fiscal',
        ),
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='simples_nacional',
        ),
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='usa_cnae_20',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cnae',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cnae_20',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='regime_fiscal',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='simples_nacional',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='usa_cnae_20',
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='classificacao_tributaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação Tributária'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='construtora',
            field=models.BooleanField(default=False, verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cooperativa',
            field=models.BooleanField(default=False, verbose_name='Cooperativa'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='gerar_esocial_domestico',
            field=models.BooleanField(default=False, verbose_name='Gerar eSocial Doméstico'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='produtor_rural',
            field=models.BooleanField(default=False, verbose_name='Produtor Rural'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='classificacao_tributaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação Tributária'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='construtora',
            field=models.BooleanField(default=False, verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cooperativa',
            field=models.BooleanField(default=False, verbose_name='Cooperativa'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='gerar_esocial_domestico',
            field=models.BooleanField(default=False, verbose_name='Gerar eSocial Doméstico'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='produtor_rural',
            field=models.BooleanField(default=False, verbose_name='Produtor Rural'),
        ),
    ]
