# Generated by Django 5.2.5 on 2025-10-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0014_consolidacao_campos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='cnae_principal',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cnae_principal',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cnaes_secundarios',
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cnae_codigo',
            field=models.CharField(blank=True, help_text='Código CNAE principal importado do Sybase', max_length=20, null=True, verbose_name='Código CNAE'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cnae_secundarios',
            field=models.TextField(blank=True, help_text='Códigos CNAE secundários separados por vírgula', null=True, verbose_name='CNAEs Secundários'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cnae_codigo',
            field=models.CharField(blank=True, help_text='Código CNAE principal importado do Sybase', max_length=20, null=True, verbose_name='Código CNAE'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cnae_secundarios',
            field=models.TextField(blank=True, help_text='Códigos CNAE secundários separados por vírgula', null=True, verbose_name='CNAEs Secundários'),
        ),
    ]
